on:
  push

name: Scan repo workflow

jobs:
  my-job:
    name: ci scan job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: scan
      uses: ./
      env:
        CS_API_TOKEN: ${{ secrets.CS_API_TOKEN }}
        CS_SCAN_URL: scanner-api.prod.eks.cybersierra.ai
